### ISSUE TITLE
How to output weekday cycle data?

### ISSUE THREAD

**Issue by pvanthony** [romcal/romcal-api#19]
Trying to get the weekday cycle data along with the other data of the day. But cannot see it. What am I missing to do?

Here is the link to the data which I am trying to get.
https://github.com/romcal/romcal/blob/dev/docs/data-output.md#weekday-cycle

Is there some configuration that needs to be added?

**Comment by tukusejssirs** [comment]
Closing, as this issues is discussed in romcal/romcal#293
